### ISSUE TITLE
Break consts

### ISSUE THREAD

**Issue by Mehrdad-Dadkhah** [zhouyl/phpfmt-tool#2]
Hi

When run  fmt tools on some code like this:

```

    const CREATED_AT = 'created_at';

    const UPDATED_AT = 'updated_at';
```

after fix it change to:

```
constCREATED_AT='created_at';constUPDATED_AT='updated_at';
```

**Comment by zhouyl** [comment]
sorry for the late reply.
I recommend you use [phpcsfixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer), I have not used phpfmt anymore.
